### ISSUE TITLE
Elasticsearch updates instead of insert

### ISSUE THREAD

**Issue by bloodcarter** [pinojs/pino-elasticsearch#12]
I use pino like this:
`    pino.info({user_id: i.user.id, task_name: i.task.instance_of_dasha_class }, "Transforming image to perseption: %j", i);     `

And sometimes is get this log enrty inserted. But most of the time I get this response from Elasticsearch:
```
Elasticsearch TRACE: 2017-09-18T08:46:02Z
  -> POST https://a8e57b5fc9b7ce0a27d15d0e0e386b8d.us-east-1.aws.found.io:9243/:9200/pino/log
  {
    "pid": 14279,
    "hostname": "ip-172-31-16-252",
    "level": 30,
    "time": "2017-09-18T08:46:02.577Z",
    "msg": "Transforming image to perseption: \\\"endpoint=RESTEndpoint:anonymous_rest_user_RZgRer8uBA/rest_default_did, task=SDConvWithClient, payload=[object Object]\\\"",
    "user_id": "hvvQPPmmXr1JFV8",
    "task_name": "SDConvWithClient",
    "v": 1
  }
  <- 200
  {
    "_index": ":9200",
    "_type": "pino",
    "_id": "log",
    "_version": 515,
    "result": "updated",
    "_shards": {
      "total": 2,
      "successful": 1,
      "failed": 0
    },
    "created": false
  }

```

That's wrong? It looks like Elasticsearch thinks this is not a new document, and updates it instead of inserting a new entry.

**Comment by mcollina** [comment]
You might be specifying some options wrong, or we might not be sanitizing them correctly: somehow you are setting `_id` to `'log'` making it an update operation rather than a create one.
Moreover, it picks the index as `':9200'` which should be `'pino'` by default.

It would be good to have a snippet to reproduce, because it is not happening here.
